name: checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar herramientas
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Validar
        run: make check
